# nginx proxy address - http://172.17.0.1:60122

name: speedtest-tracker
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      DB_CONNECTION: sqlite
      PUBLIC_DASHBOARD: true
      APP_NAME: ${APP_ORG_NAME:-Speedtest Results}
      TZ: ${TZ:-America/New_York}
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_SCHEDULE:-0 */4 * * *}
      DISPLAY_TIMEZONE: ${TZ:-America/New_York}
      APP_URL: https://${BASE_HOST_NAME:-$HOSTNAME}.${BASE_DOMAIN_NAME:-example.com}
      ASSET_URL: https://${BASE_HOST_NAME:-$HOSTNAME}.${BASE_DOMAIN_NAME:-example.com}
      ADMIN_NAME: ${APP_ADMIN_USER:-administrator}
      ADMIN_EMAIL: ${APP_ADMIN_USER:-admin@example.com}
      ADMIN_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      APP_KEY: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      PRUNE_RESULTS_OLDER_THAN: ${PRUNE_RESULTS_OLDER_THAN:-0}
      SPEEDTEST_SERVERS: ${SPEEDTEST_SERVERS:-}
      CONTAINER_NAME: speedtest-tracker-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:60122:80'
    volumes:
      - './volumes/config/speedtest-tracker:/config'
    healthcheck:
      test: curl -q -LSsf "http://127.0.0.1/api/healthcheck" | grep -q "ok" || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://speedtest-tracker-app:80'
      - 'cloudflare.hostname=speedtest-tracker.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.speedtest-tracker-app.entrypoints=http'
      - 'traefik.http.routers.speedtest-tracker-app-secure.tls=true'
      - 'traefik.http.routers.speedtest-tracker-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.speedtest-tracker-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.speedtest-tracker-app.middlewares=speedtest-tracker-app-https-redirect'
      - 'traefik.http.routers.speedtest-tracker-app-secure.entrypoints=https'
      - 'traefik.http.routers.speedtest-tracker-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.speedtest-tracker-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.speedtest-tracker-app-secure.service=speedtest-tracker-app'
      - 'traefik.http.services.speedtest-tracker-app.loadbalancer.server.port=80'
    networks:
      - speedtest-tracker
      - proxy
      - cloudflare

networks:
  speedtest-tracker:
    name: speedtest-tracker
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
